name: Bundle

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Set up NodeJS
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: sh bundle.sh
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: binaries/